name: cat_breeds
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

flutter_native_splash:
  color: "#AE28FA"
  image: assets/images/splash-image.png
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: scaleAspectFit

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
    
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.3
  google_fonts: ^6.2.1
  go_router: ^14.6.1
  http: ^1.2.2
  provider: ^6.1.2
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/gifs/
